use_frameworks!

platform :ios, '10.0'

target 'garyPrivatePodTest_Example' do
  pod 'garyPrivatePodTest', :path => '../'

  target 'garyPrivatePodTest_Tests' do
    inherit! :search_paths

    
  end
end
